### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AndyLonly** [dr413677671/PromptGallery-stable-diffusion-webui#10]
Installation method: via webui

Trigger: generate the preview image

Trackback：
```py
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\scripts\prompt_gallery.py", line 590, in run
    proc = process_images(copy_p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 430, in process_images
    res = process_images_inner(p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 554, in process_images_inner
    images.save_image(Image.fromarray(x_sample), p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p, suffix="-before-face-restoration")
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\images.py", line 519, in save_image
    image.save(fullfn, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dr413677671\\Downloads\\stable-diffusion-webui-master\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\General_high_res\\./00000-228796099-portrait,fullbody,complex,extremelydetailed,elegant,CG,masterpiece,bestquality,conceptart,illustration,highres,original,-before-face-restoration.png'
```

**Comment by dr413677671** [comment]
Added a fix. Could you try reinstall?

**Comment by AndyLonly** [comment]
Trackback:
```py
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dr413677671\\Downloads\\stable-diffusion-webui-master\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\General_ice_high_res\\00000-1721108282-flowing ice, portrait, focus on face, complex, extremely detailed , elegant, CG,  (an extremely delicate and beautiful girl), in-before-face-restoration.png'
```

**Comment by dr413677671** [comment]
Could you paste the whole log?

**Comment by dr413677671** [comment]
It seems that my callback code line is different from your WebUI.
`images.save_image(Image.fromarray(x_sample), p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p, suffix="-before-face-restoration")` is line 584 in my webui.
Do you try git pull to update the Webui?

I noticed there is a param -before-face-restoration in your output filename. Did you add restore_faces in param? How did you add this could you screenshot?

**Comment by AndyLonly** [comment]
```bat
>>git pull
remote: Enumerating objects: 374, done.
remote: Counting objects: 100% (312/312), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 374 (delta 252), reused 258 (delta 218), pack-reused 62
Receiving objects: 100% (374/374), 183.91 KiB | 980.00 KiB/s, done.
Resolving deltas: 100% (252/252), completed with 80 local objects.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
   44c46f0..7cea280  master     -> origin/master
Updating 44c46f0..7cea280
Fast-forward
 README.md                                          |    1 +
 extensions-builtin/LDSR/ldsr_model_arch.py         |    1 +
 extensions-builtin/LDSR/scripts/ldsr_model.py      |    2 +-
 extensions-builtin/LDSR/sd_hijack_ddpm_v1.py       | 1449 ++++++++++++++++++++
 .../javascript/prompt-bracket-checker.js           |  107 ++
 javascript/hints.js                                |    1 +
 javascript/ui.js                                   |    9 +
 launch.py                                          |    4 +-
 modules/api/api.py                                 |    7 +-
 modules/extras.py                                  |   37 +-
 modules/generation_parameters_copypaste.py         |    4 +-
 modules/images.py                                  |   51 +-
 modules/processing.py                              |   62 +-
 modules/safety.py                                  |   42 -
 modules/scripts.py                                 |   20 +
 modules/sd_hijack.py                               |   14 +-
 modules/sd_hijack_unet.py                          |   30 +
 modules/sd_models.py                               |   48 +
 modules/sd_vae.py                                  |   37 +-
 modules/shared.py                                  |    3 +-
 modules/ui.py                                      |   56 +-
 modules/ui_extensions.py                           |   13 +-
 requirements.txt                                   |    2 +-
 requirements_versions.txt                          |    1 -
 script.js                                          |    7 +-
 scripts/prompt_matrix.py                           |    7 +-
 scripts/sd_upscale.py                              |   15 +-
 style.css                                          |    2 +-
 webui-macos-env.sh                                 |    6 +
 webui.py                                           |    2 +-
 30 files changed, 1869 insertions(+), 171 deletions(-)
 create mode 100644 extensions-builtin/LDSR/sd_hijack_ddpm_v1.py
 create mode 100644 extensions-builtin/prompt-bracket-checker/javascript/prompt-bracket-checker.js
 delete mode 100644 modules/safety.py
 create mode 100644 modules/sd_hijack_unet.py
>>git status
On branch master
Your branch is up to date with 'origin/master'.
```

```py
Traceback (most recent call last):
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\scripts\prompt_gallery.py", line 603, in run
    proc = process_images(copy_p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 589, in process_images_inner
    images.save_image(Image.fromarray(x_sample), p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p, suffix="-before-face-restoration")
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\images.py", line 536, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\images.py", line 516, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dr413677671\\Downloads\\stable-diffusion-webui-master\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\General_ice_high_res\\00000-95817282-flowing ice, portrait, focus on face, complex, extremely detailed , elegant, CG,  (an extremely delicate and beautiful girl), in-before-face-restoration.tmp'
```

Yes, I am using the latest webui via git pull
[images.save_image(Image.fromarray(x_sample), p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p, suffix="-before-face-restoration")](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/7cea280a8fd9b7e3cc65a1719d6371d69013c9bb/modules/processing.py#L589)

**Comment by dr413677671** [comment]
I noticed there is a param -before-face-restoration in your output filename. Did you add restore_faces in param? How did you add this could you screenshot?

**Comment by dr413677671** [comment]
Please try remove save_images_before_face_restoration in customize param.

**Comment by AndyLonly** [comment]
Fix by remove save images before face restoration
![image](https://user-images.githubusercontent.com/15814794/206860697-bf159373-4795-4b1b-b03f-14195bd482be.png)
But can't select the preview image now(No error message)
![image](https://user-images.githubusercontent.com/15814794/206860895-98b69aaa-f8fe-4297-a037-3f46d8b23266.png)
![image](https://user-images.githubusercontent.com/15814794/206861025-f74101af-d543-4903-a4c7-4ccfd6953eec.png)
![image](https://user-images.githubusercontent.com/15814794/206860789-d86230ca-d2ba-40c6-a288-ec027438a5a1.png)

**Comment by AndyLonly** [comment]
```py
Traceback (most recent call last):
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\txt2img.py", line 46, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\scripts\prompt_gallery.py", line 603, in run
    proc = process_images(copy_p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\processing.py", line 607, in process_images_inner
    images.save_image(image, p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\images.py", line 536, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\modules\images.py", line 516, in _atomically_save_image
    image_to_save.save(temp_file_path, format=image_format, quality=opts.jpeg_quality, pnginfo=pnginfo_data)
  File "C:\Users\dr413677671\Downloads\stable-diffusion-webui-master\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dr413677671\\Downloads\\stable-diffusion-webui-master\\extensions\\PromptGallery-stable-diffusion-webui\\assets\\preview\\General_ice_high_res\\00000-1676927119-flowing ice, portrait, focus on face, complex, extremely detailed , elegant, CG,  (an extremely delicate and beautiful girl), in.tmp'
```
got error after select save all image
![image](https://user-images.githubusercontent.com/15814794/206861197-0aadf6db-0302-41f4-901d-6a7df0314bd2.png)

**Comment by dr413677671** [comment]
Thanks @AndyLonly, I tried the same setup but still could not produce from my side. No idea why.

At the same time I added a workaround to reset the user config to default if the script is enabled.
![image](https://user-images.githubusercontent.com/32362729/206861692-7906e911-6d86-4fec-bec0-2ea12f9cda06.png)

**Comment by dr413677671** [comment]
I assume that root cause comes from other config item.

**Comment by AndyLonly** [comment]
I'll try to use debug mode later to check what's causing the problem
