### ISSUE TITLE
AssertionError: trying to open image file not in temporary directory

### ISSUE THREAD

**Issue by djkacevedo** [dr413677671/PromptGallery-stable-diffusion-webui#28]
This happens after choosing an image and clicking select after running the script.

```
Traceback (most recent call last):
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\dev\stable-diffusion-webui-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\dev\stable-diffusion-webui-main\scripts\prompt_gallery.py", line 642, in <lambda>
    fn=lambda x: image_url(x),
  File "D:\dev\stable-diffusion-webui-main\scripts\prompt_gallery.py", line 565, in image_url
    assert normfn.startswith(tempdir), 'trying to open image file not in temporary directory'
AssertionError: trying to open image file not in temporary directory
```

**Comment by dr413677671** [comment]
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/32362729/224552523-7803a3d0-9c28-43ee-b688-a42391a6f4a9.png">
Could you try modify the settings. This look like a setting problem but hard to find out which item is the cause.
